
# winpty docker exec -it phusion bash

# 1. connection from phusion to apptest:
# ssh -i /service/ssh/id_rsa root@apptest

# 2. connection from phusion to sge:
# ssh -i /service/ssh/id_rsa sgeuser@sge

# check SSH:
# ssh -i key/id_rsa root@localhost -p 2222


services:

  phusion:
    build:
      context: ./image
    image: phusionimg
    container_name: phusion
    volumes:
      - shared-data:/shared
    command: /bin/bash -c "
      cp /service/ssh/id_rsa.pub /shared/id_rsa.pub && \
      /usr/sbin/sshd -D"


  apptest:
    image: phusionimg
    depends_on:
      - phusion
    container_name: apptest
    ports:
      - "2222:22"
    volumes:
      - shared-data:/shared
    command: /bin/bash -c "
      cat /shared/id_rsa.pub >> /root/.ssh/authorized_keys && \
      /usr/sbin/sshd -D"


  sge:
    image: diixo/sge-base:latest
    container_name: sge
    stdin_open: true
    tty: true
    volumes:
      - shared-data:/shared
    command: /bin/bash -c "
      mkdir -p /home/sgeuser/.ssh && \
      touch /home/sgeuser/.ssh/authorized_keys && \
      cat /shared/id_rsa.pub >> /home/sgeuser/.ssh/authorized_keys && \
      /usr/sbin/sshd -D"


volumes:
  shared-data:
