# winpty docker exec -it phusion bash

# winpty docker exec -it sge bash

# check SSH:
# ssh -i key/id_rsa root@localhost -p 2222


services:

  app:
    build:
      context: ./image
    image: phusionimg
    container_name: phusion
    ports:
      - "2222:22"
    volumes:
      - shared-data:/shared
    command: "/usr/sbin/sshd -D && cp /service/ssh/id_rsa.pub /shared/id_rsa.pub"

  sge:
    image: diixo/sge-new:latest
    depends_on:
      - app
    container_name: sge
    stdin_open: true
    tty: true

    command: /bin/bash -c "
      mkdir -p /home/sgeuser/.ssh && \
      chmod 700 /home/sgeuser/.ssh && \
      cat /shared/id_rsa.pub >> /home/sgeuser/.ssh/authorized_keys && \
      chown sgeuser:sgeuser /home/sgeuser/.ssh* && \
      /usr/sbin/sshd -D"
    volumes:
      - shared-data:/shared

volumes:
  shared-data:
