# winpty docker exec -it phusion bash

# winpty docker exec -it sge bash

# check SSH:
# ssh -i key/id_rsa root@localhost -p 2222


services:

  app:
    build:
      context: ./image
    image: phusionimg
    container_name: phusion
    ports:
      - "2222:22"
    command: "/usr/sbin/sshd -D &&
              cp /service/ssh/id_rsa.pub /shared/id_rsa.pub"
    volumes:
      - shared-data:/shared

  sge:
    image: diixo/sge-new:latest
    container_name: sge
    stdin_open: true
    tty: true

      #cat /shared/id_rsa.pub >> /home/sgeuser/.ssh/authorized_keys && \
      #chmod 600 /home/sgeuser/.ssh/authorized_keys && \
    command: /bin/bash -c "
      mkdir -p /home/sgeuser/.ssh && \
      chmod 700 /home/sgeuser/.ssh && \
      chown sgeuser:sgeuser /home/sgeuser/.ssh* && \
      /usr/sbin/sshd -D"
    volumes:
      - shared-data:/shared

volumes:
  shared-data:
